language: bash
os:
  - linux
install:
  - wget https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz --no-cache
  - tar -xf zig-linux-*
git:
  depth: false
script:
  - zig-linux-*/zig version
  - zig-linux-*/zig test crc.zig
  - zig-linux-*/zig test crc.zig --release-fast
  - zig-linux-*/zig test crc.zig --release-safe
  - zig-linux-*/zig test crc.zig --release-small
